CREATE TABLE MODEL
(
	ID NUMBER(19) NOT NULL,
	VAL VARCHAR2(50) NOT NULL,
);


CREATE TABLE MUSIC
(
    ARTIST VARCHAR2(19) NOT NULL,
    NAME VARCHAR2(50) NOT NULL,
    STYLE VARCHAR2(50) NOT NULL,
);

CREATE TABLE SAMPLE
(
    ID VARCHAR2(50) NOT NULL,
    STYLE VARCHAR2(50) NOT NULL,
);

CREATE TABLE SAMPLE_MATCH
(
    SAMPLE1 VARCHAR2(50) NOT NULL,
    SAMPLE2 VARCHAR2(50) NOT NULL,
    RULE VARCHAR2(50) NOT NULL,
);


