sudo: required
language: java
jdk:
  - oraclejdk11
env:
  global:
  - secure: "encrypted-sonar-token"
#  - secure: "encrypted-dockerhub-username"
#  - secure: "encrypted-dockerhub-password"
  - secure: "encrypted-heroku-api-key"
  - COMMIT=${TRAVIS_COMMIT::7}

#addons:
#  sonarcloud:
#    organization: "sivaprasadreddy-github"
#    token:
#      secure: $SONAR_TOKEN

services:
  - docker
  
notifications:
  email:
    - 00jmsmachado@gmail.com
  on_success: always
  on_failure: always

   
script:
  mvn clean install
#  - docker run stephengrider/react-test npm test -- --coverage
#  - ./mvnw clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar

after_success:
  - docker login -u $DOCKER_ID -p "$DOCKER_PWD
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH&amp;amp;amp;amp;amp;amp;amp;lt;span data-mce-type="bookmark" style="display: inline-block; width: 0px; overflow: hidden; line-height: 0;" class="mce_SELRES_start"&amp;amp;amp;amp;amp;amp;amp;gt;&amp;amp;amp;amp;amp;amp;amp;lt;/span&amp;amp;amp;amp;amp;amp;amp;gt;; fi`
  - export IMAGE_NAME=machadojo/perfectmatch-webapp
  - docker build -t $IMAGE_NAME:$COMMIT .
  - docker tag $IMAGE_NAME:$COMMIT $IMAGE_NAME:$TAG
  - docker push $IMAGE_NAME

#  - docker build -t machadojo/perfectmatch-webapp ./perfectmatch 
  # Log in to the docker CLI
 # - echo "$DOCKER_PWD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
 # - docker push machadojo/perfectmatch-webapp