/*
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.perfectmatch.web.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Details of the match - first step process without envolving music samples
 */
@ApiModel(description = "Details of the match - first step process without envolving music samples")
public class Match {
  @JsonProperty("id")
  private String id = null;

  @JsonProperty("musicNameThat")
  private String musicNameThat = null;

  @JsonProperty("musicNameThis")
  private String musicNameThis = null;

  @JsonProperty("rule")
  private String rule = null;

  public Match id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public Match musicNameThat(String musicNameThat) {
    this.musicNameThat = musicNameThat;
    return this;
  }

   /**
   * Name of the music 2
   * @return musicNameThat
  **/
  @ApiModelProperty(value = "Name of the music 2")
  public String getMusicNameThat() {
    return musicNameThat;
  }

  public void setMusicNameThat(String musicNameThat) {
    this.musicNameThat = musicNameThat;
  }

  public Match musicNameThis(String musicNameThis) {
    this.musicNameThis = musicNameThis;
    return this;
  }

   /**
   * Name of the music 1
   * @return musicNameThis
  **/
  @ApiModelProperty(value = "Name of the music 1")
  public String getMusicNameThis() {
    return musicNameThis;
  }

  public void setMusicNameThis(String musicNameThis) {
    this.musicNameThis = musicNameThis;
  }

  public Match rule(String rule) {
    this.rule = rule;
    return this;
  }

   /**
   * Rule used in the match, default is by key and same artist 
   * @return rule
  **/
  @ApiModelProperty(value = "Rule used in the match, default is by key and same artist ")
  public String getRule() {
    return rule;
  }

  public void setRule(String rule) {
    this.rule = rule;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Match match = (Match) o;
    return Objects.equals(this.id, match.id) &&
        Objects.equals(this.musicNameThat, match.musicNameThat) &&
        Objects.equals(this.musicNameThis, match.musicNameThis) &&
        Objects.equals(this.rule, match.rule);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, musicNameThat, musicNameThis, rule);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Match {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    musicNameThat: ").append(toIndentedString(musicNameThat)).append("\n");
    sb.append("    musicNameThis: ").append(toIndentedString(musicNameThis)).append("\n");
    sb.append("    rule: ").append(toIndentedString(rule)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

