/*
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.perfectmatch.web.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.perfectmatch.web.client.model.URL;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Details of the Sample
 */
@ApiModel(description = "Details of the Sample")
public class Sample {
  @JsonProperty("id")
  private String id = null;

  @JsonProperty("location")
  private URL location = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("timestamp")
  private Integer timestamp = null;

  public Sample id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public Sample location(URL location) {
    this.location = location;
    return this;
  }

   /**
   * Location of the file in the storage
   * @return location
  **/
  @ApiModelProperty(value = "Location of the file in the storage")
  public URL getLocation() {
    return location;
  }

  public void setLocation(URL location) {
    this.location = location;
  }

  public Sample name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Name of the music
   * @return name
  **/
  @ApiModelProperty(value = "Name of the music")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Sample timestamp(Integer timestamp) {
    this.timestamp = timestamp;
    return this;
  }

   /**
   * Specific position of the original music
   * @return timestamp
  **/
  @ApiModelProperty(value = "Specific position of the original music")
  public Integer getTimestamp() {
    return timestamp;
  }

  public void setTimestamp(Integer timestamp) {
    this.timestamp = timestamp;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Sample sample = (Sample) o;
    return Objects.equals(this.id, sample.id) &&
        Objects.equals(this.location, sample.location) &&
        Objects.equals(this.name, sample.name) &&
        Objects.equals(this.timestamp, sample.timestamp);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, location, name, timestamp);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Sample {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    location: ").append(toIndentedString(location)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    timestamp: ").append(toIndentedString(timestamp)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

