/*
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.perfectmatch.web.client.api;

import com.perfectmatch.web.client.model.Music;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for MusicControllerApi
 */
@Ignore
public class MusicControllerApiTest {

    private final MusicControllerApi api = new MusicControllerApi();

    
    /**
     * createMusic
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createMusicUsingPOSTTest() {
        Music resource = null;
        Music response = api.createMusicUsingPOST(resource);

        // TODO: test validations
    }
    
    /**
     * Find all musics - without pagination
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAllMusicsUsingGETTest() {
        List<Music> response = api.getAllMusicsUsingGET();

        // TODO: test validations
    }
    
    /**
     * Find Music by name
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getMusicByNameUsingGETTest() {
        String name = null;
        Music response = api.getMusicByNameUsingGET(name);

        // TODO: test validations
    }
    
    /**
     * updateMusic
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateMusicUsingPUTTest() {
        Music resource = null;
        Music response = api.updateMusicUsingPUT(resource);

        // TODO: test validations
    }
    
}
