/*
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.perfectmatch.web.client.api;

import com.perfectmatch.web.client.model.PerfectMatch;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for PerfectMatchControllerApi
 */
@Ignore
public class PerfectMatchControllerApiTest {

    private final PerfectMatchControllerApi api = new PerfectMatchControllerApi();

    
    /**
     * createPerfectMatch
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createPerfectMatchUsingPOSTTest() {
        PerfectMatch resource = null;
        PerfectMatch response = api.createPerfectMatchUsingPOST(resource);

        // TODO: test validations
    }
    
    /**
     * Find all Perfect Matchs - without pagination
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findAllPerfectMatchsUsingGETTest() {
        List<PerfectMatch> response = api.findAllPerfectMatchsUsingGET();

        // TODO: test validations
    }
    
    /**
     * Find Match by name
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getPerfectMatchByNameUsingGETTest() {
        String name = null;
        PerfectMatch response = api.getPerfectMatchByNameUsingGET(name);

        // TODO: test validations
    }
    
}
