/*
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.perfectmatch.web.client.api;

import com.perfectmatch.web.client.model.Sample;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for SampleControllerApi
 */
@Ignore
public class SampleControllerApiTest {

    private final SampleControllerApi api = new SampleControllerApi();

    
    /**
     * createSample
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createSampleUsingPOSTTest() {
        Sample resource = null;
        Sample response = api.createSampleUsingPOST(resource);

        // TODO: test validations
    }
    
    /**
     * Find all Samples - without pagination
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findAllSamplesUsingGETTest() {
        List<Sample> response = api.findAllSamplesUsingGET();

        // TODO: test validations
    }
    
    /**
     * Find Match by name
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getSampleByNameUsingGETTest() {
        String name = null;
        Sample response = api.getSampleByNameUsingGET(name);

        // TODO: test validations
    }
    
}
